[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "pairing-crypto"
version = "0.1.0"

[dependencies]
ff = { version = "0.6", package = "ff-zeroize" }
hkdf = "0.9"
pairings = { version = "0.20", path = "pairings" }
rand = "0.7"
serde = { version = "1.0", feature = ["derive"] }
serde-big-array = "0.3"
sha2 = "0.9"
zeroize = { version = "1.2", feature = ["zeroize_derive"] }

[dev-dependencies]
base64-url = "1.4"
