[package]
authors = ["Michael Lodder <redmike7@gmail.com>", "Tobias Looker <tobias.looker@mattr.global"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "pairing_crypto"
version = "0.1.0"

[features]
default = []
test = ["rand_xorshift"]
wasm = ["getrandom", "wasm-bindgen"]

[dependencies]
digest = "0.9"
ff = "0.9"
group = "0.9"
hashbrown = "0.11"
heapless = "0.6"
hkdf = "0.10"
rand = { version = "0.8", features = ["getrandom"] }
getrandom = { version = "0.2", optional = true, features = ["js"] }
rand_chacha = "0.3"
rand_core = "0.6"
rand_xorshift = { version = "0.3", optional = true }
pairing = "0.19"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
sha3 = "0.9"
subtle = "2.4"
wasm-bindgen = { version = "0.2", optional = true }
zeroize = { version  ="1.3", features = ["zeroize_derive"] }

[dev-dependencies]
base64-url = "1.4"
hex = "0.4"
rand_xorshift = "0.3"
