[package]
authors = ["Michael Lodder <redmike7@gmail.com>", "Tobias Looker <tobias.looker@mattr.global"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "pairing_crypto"
version = "0.1.0"

[dependencies]
digest = "0.9"
ff = "0.9"
group = "0.9"
hashbrown = "0.11"
heapless = "0.6"
hkdf = "0.10"
rand = "0.8"
rand_chacha = "0.3"
rand_core = "0.6"
pairing = "0.19"
serde = { version = "1.0", features = ["derive"] }
sha2 = "0.9"
sha3 = "0.9"
subtle = "2.4"
zeroize = { version  ="1.2", features = ["zeroize_derive"] }

[dev-dependencies]
base64-url = "1.4"
hex = "0.4"
rand_xorshift = "0.3"
