[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "pairing-crypto"
version = "0.1.0"

[dependencies]
bls12_381_plus = "0.4"
ff = "0.9"
group = "0.9"
rand = "0.8"
signature_bls = "0.1"


[dev-dependencies]
