[package]
authors = ["Michael Lodder <redmike7@gmail.com>"]
edition = "2018"
license = "Apache-2"
readme = "README.md"
name = "pairing-crypto"
version = "0.1.0"

[dependencies]
bls12_381_plus = { version = "0.4", path = "bls12_381_plus" }
digest = "0.9"
ff = "0.9"
group = "0.9"
hashbrown = "0.11"
hkdf = "0.10"
rand = "0.8"
rand_chacha = "0.3"
rand_core = "0.6"
serde = { version = "1.0", features = ["derive"] }
sha3 = "0.9"
bls = { version = "0.1", path = "bls" }
subtle = "2.4"
zeroize = "1.2"


[dev-dependencies]
base64-url = "1.4"
rand_xorshift = "0.3"
