name: ci-detox-android

on:
  pull_request:
    branches:
      - master

jobs:
  java-wrapper:
    name: Build Java Wrapper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wrappers/react-native
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      # Needed to resolve any private git based dependencies like https://github.com/mattrglobal/blstrs
      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@836c84ec59a0e7bc0eabc79988384eb567561ee2 # pin@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # pin@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Libraries for Android
        run: yarn build:android

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ci-detox-android-artifacts-libs-${{ github.sha }}
          path: wrappers/react-native/android/lib
          retention-days: 1

  android:
    name: Detox Android E2E Testing
    needs: [java-wrapper]
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: "--max-old-space-size=5120"

    defaults:
      run:
        working-directory: wrappers/react-native

    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3.5.1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Download Android Libraries
        uses: actions/download-artifact@v3
        with:
          name: ci-detox-android-artifacts-libs-${{ github.sha }}
          path: wrappers/react-native/android/lib

      - name: Inspect Android Libraries
        run: ls -R android/lib

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Example App Install Dependencies
        working-directory: wrappers/react-native/example
        run: yarn install --frozen-lockfile

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Detox Build Android Configuration
        working-directory: wrappers/react-native
        run: yarn detox:build:android

      - name: Inspect Linked Libraries
        run: ls -R android/src/main/jniLibs

      - name: Get device name
        id: device
        run: node -e "console.log('AVD_NAME=' + require('./example/.detoxrc.json').devices.emulator.device.avdName)" >> $GITHUB_OUTPUT

      - name: Inspect environment
        run: echo $ANDROID_HOME

      - name: Free up space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost

      - name: Download Android Build Tools
        timeout-minutes: 5
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "build-tools;34.0.0"
          cd $ANDROID_SDK_ROOT/build-tools/34.0.0/
          ln -sf d8 dx
          cd lib
          ln -sf d8.jar dx.jar

      - name: Start adb server
        id: adb_start
        run: $ANDROID_HOME/platform-tools/adb start-server

      - name: Download Android Emulator Image
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-29;google_apis;x86_64"
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name emu_1 --device "Nexus 5X" -k 'system-images;android-29;google_apis;x86_64'
          echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force --name emu_2 --device "Nexus 5X" -k 'system-images;android-29;google_apis;x86_64'
          $ANDROID_HOME/emulator/emulator -list-avds

      - name: Launch emulators
        if: steps.adb_start.outcome == 'success'
        run: |
           /usr/local/lib/android/sdk/emulator/emulator -port 5554 -avd emu_1 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &
           /usr/local/lib/android/sdk/emulator/emulator -port 5556 -avd emu_2 -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none &

      - name: Wait for emulators to boot
        id: booted
        timeout-minutes: 2
        run: |
            set -x
            while ! $ANDROID_HOME/platform-tools/adb -s emulator-5554 shell getprop sys.boot_completed 2> /dev/null || \
                  ! $ANDROID_HOME/platform-tools/adb -s emulator-5556 shell getprop sys.boot_completed 2> /dev/null
            do
              $ANDROID_HOME/platform-tools/adb devices -l
              sleep 0.3
            done

      - name: KeyGen test
        working-directory: wrappers/react-native
        if: steps.booted.outcome == 'success'
        run: yarn detox:android:ci -n emu_1 /__tests__/keyGen.e2e.ts

      - name: Signature test
        working-directory: wrappers/react-native
        if: steps.booted.outcome == 'success'
        run: yarn detox:android:ci -n emu_2 /__tests__/signature.e2e.ts

      - name: Archive detox failed test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detox-artifacts-${{ github.sha }}
          path: wrappers/react-native/example/detox-artifacts
          retention-days: 1
