name: ci-wrapper-wasm

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test:
    name: Build & Test WASM Wrapper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wrappers/wasm
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: "rustfmt, clippy"

      - name: Run cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--all -- --check"

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Run yarn build
        run: yarn build

      - name: Run yarn test
        run: yarn test

      - name: Run yarn benchmark
        run: yarn benchmark
