name: ci-wrapper-c

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test:
    name: Build & Test C Wrapper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wrappers/c
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: "rustfmt, clippy"

      - name: Run cargo format
        run: make format
        shell: bash

      - name: Run cargo clippy
        run: make clippy
        shell: bash

      - name: Run cargo check
        run: make check
        shell: bash

      - name: Run cargo audit
        run: make audit
        shell: bash

      - name: Run cargo build
        run: make build
        shell: bash

      - name: Generate header
        run: make generate_headers
        shell: bash

      - name: Run tests
        run: make test
        shell: bash
