name: ci-wrapper-c

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_test:
    name: Build & Test C Wrapper
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./wrappers/c
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: "rustfmt, clippy"

      - name: Run cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--all -- --check"

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit

      - name: Generate header
        run: make generate_headers
        shell: bash

      - name: Run tests
        run: make test
        shell: bash
